//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAPrinter
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerItem
    {
        public long Id { get; set; }
        public string baserecord { get; set; }
        public string PrefixRecord { get; set; }
        public string SuffixRecord { get; set; }
        public string ModifierRecord { get; set; }
        public string TransmuteRecord { get; set; }
        public Nullable<long> Seed { get; set; }
        public string MateriaRecord { get; set; }
        public string RelicCompletionBonusRecord { get; set; }
        public Nullable<long> RelicSeed { get; set; }
        public string EnchantmentRecord { get; set; }
        public Nullable<int> PrefixRarity { get; set; }
        public Nullable<long> UNKNOWN { get; set; }
        public Nullable<long> EnchantmentSeed { get; set; }
        public Nullable<long> MateriaCombines { get; set; }
        public Nullable<long> StackCount { get; set; }
        public string Name { get; set; }
        public string namelowercase { get; set; }
        public string Rarity { get; set; }
        public Nullable<double> LevelRequirement { get; set; }
        public string Mod { get; set; }
        public Nullable<bool> IsHardcore { get; set; }
        public string azpartition_v2 { get; set; }
        public string azuuid_v2 { get; set; }
        public Nullable<long> created_at { get; set; }
    }
}
